[project]
name = "pac-man"
version = "0.3.0"
description = "Pacman 42 School project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame-ce",
    "mazegenerator",
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=1.16.1",
    "pytest>=9.0.2",
]

[tool.uv.sources]
mazegenerator = { path = "packages/mazegenerator-00001-py3-none-any.whl" }

[tool.mypy]
mypy_path = "src"
explicit_package_bases = true

[[tool.mypy.overrides]]
module = "mazegenerator.*"
ignore_missing_imports = true